spring.application.name=Secure-Todo

spring.datasource.url=jdbc:postgresql://localhost:5432/todo_db
# no hardcoded secrets
spring.datasource.username=${DB_USER:admin}
spring.datasource.password=${DB_PASSWD:secret_password_local}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Ativa o padrão RFC 7807 para respostas de erro
spring.mvc.problemdetails.enabled=true

# VULNERABLE [API08:2023]: Security Misconfiguration
server.error.include-stacktrace=always
server.error.include-message=always
server.error.include-binding-errors=always

security.jwt.secret=${JWT_SECRET:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970}
# Tempo de expiração: 1 dia (86400000 ms) ou 1 hora (3600000 ms)
security.jwt.expiration=3600000

springdoc.swagger-ui.tags-sorter=alpha
springdoc.swagger-ui.operations-sorter=alpha

springdoc.swagger-ui.enabled=true
management.endpoints.web.exposure.include=* server.error.include-stacktrace=always

