# Desabilita o Swagger em Produção
springdoc.api-docs.enabled=false
springdoc.swagger-ui.enabled=false

# Ativa o padrão RFC 7807 para respostas de erro
spring.mvc.problemdetails.enabled=true

# Restringe o Actuator apenas para métricas de saúde (Health Check)
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=never

# Jamais mostre o Stack Trace para o cliente final
server.error.include-stacktrace=never
server.error.include-message=never


